// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMVkJVEu6I0mLYsq-S2Iv8DSLEtMyVwQw',
    appId: '1:786402599068:web:dfe3925955f18668684d59',
    messagingSenderId: '786402599068',
    projectId: 'safechat-4c782',
    authDomain: 'safechat-4c782.firebaseapp.com',
    storageBucket: 'safechat-4c782.firebasestorage.app',
    measurementId: 'G-Q88EG14Y75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxVaVwbC0IHQvsqCw39e4EieUDkSwbO80',
    appId: '1:786402599068:android:240862a9e19a152f684d59',
    messagingSenderId: '786402599068',
    projectId: 'safechat-4c782',
    storageBucket: 'safechat-4c782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClptSrG9xYGZCtckP15yAm8uzzZRFg3jY',
    appId: '1:786402599068:ios:218948b30c6598ea684d59',
    messagingSenderId: '786402599068',
    projectId: 'safechat-4c782',
    storageBucket: 'safechat-4c782.firebasestorage.app',
    iosBundleId: 'com.example.emailchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClptSrG9xYGZCtckP15yAm8uzzZRFg3jY',
    appId: '1:786402599068:ios:218948b30c6598ea684d59',
    messagingSenderId: '786402599068',
    projectId: 'safechat-4c782',
    storageBucket: 'safechat-4c782.firebasestorage.app',
    iosBundleId: 'com.example.emailchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMVkJVEu6I0mLYsq-S2Iv8DSLEtMyVwQw',
    appId: '1:786402599068:web:fa8735100a661b4f684d59',
    messagingSenderId: '786402599068',
    projectId: 'safechat-4c782',
    authDomain: 'safechat-4c782.firebaseapp.com',
    storageBucket: 'safechat-4c782.firebasestorage.app',
    measurementId: 'G-Q2X5N0Q87Q',
  );

}