// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA73YAzjcrvp1Ow7waC6ek50J_Jg8QrhPU',
    appId: '1:958437378846:web:aa7b7f2dac13dff48c570f',
    messagingSenderId: '958437378846',
    projectId: 'safechat-76c57',
    authDomain: 'safechat-76c57.firebaseapp.com',
    storageBucket: 'safechat-76c57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIQoHSQ7BJbKxU8aGSZQV7AYmZqshvl4w',
    appId: '1:958437378846:android:bda1e93029e209a88c570f',
    messagingSenderId: '958437378846',
    projectId: 'safechat-76c57',
    storageBucket: 'safechat-76c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ynQCEclXmomslwPprDFfe7n6y0JlTRA',
    appId: '1:958437378846:ios:659b5f268e9be4448c570f',
    messagingSenderId: '958437378846',
    projectId: 'safechat-76c57',
    storageBucket: 'safechat-76c57.appspot.com',
    iosBundleId: 'com.example.emailchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9ynQCEclXmomslwPprDFfe7n6y0JlTRA',
    appId: '1:958437378846:ios:a0ee775560eace238c570f',
    messagingSenderId: '958437378846',
    projectId: 'safechat-76c57',
    storageBucket: 'safechat-76c57.appspot.com',
    iosBundleId: 'com.example.emailchat.RunnerTests',
  );
}
